Домашняя работа - Сарсенбаев Б.А.
Beken-S/js-part-0 pull request #1
Opened 2022-12-11 19:09 UTC by Beken-S

Для того чтобы функция ``test`` могла работать с массивами примитивов:
1. Написал функцию ``compareTowArrays`` для сравнения двух массивов.
2. Изменил функцию ``areEqual`` чтобы она могла выполнять сравнение массивов.

Реализовал логику всех заданных функций.
Где необходимо было исправил тесты.
Написла тесты для функции ``compareTowArrays`` и несколько тестов для существующих блоков тестов.

2022-12-15 20:39 UTC, ipetropolsky requested changes

2022-12-15 20:39 UTC, ipetropolsky commented on index.js
> +    } while (tasksA.length > 0);
Хорошая идея, но очень сложная. Во-первых, задача была сравнить массивы примитивов, а не массивы массивов. Во-вторых, цикл в цикле сразу настораживает, к тому же у `while` не очень чёткое условие выхода. 

Давай упростим это как-нибудь. Если хочешь сравнить массивы внутри массивов, у тебя же уже есть `compareTwoArrays`.

2022-12-15 20:39 UTC, ipetropolsky commented on index.js
> +const compareTowArrays = (a, b) => {
```suggestion
const compareTwoArrays = (a, b) => {
```

2022-12-15 20:39 UTC, ipetropolsky commented on index.js
> +        throw new Error('One of the arguments is not an array!');
При таком поведении тебе всегда придётся проверять типы перед тем как вызвать эту функцию. Это правильно, в принципе, но заморочно. Я бы просто вернул `false`, если пришла фигня.

Но такая чёткость как у тебя тоже полезна, например, в моём варианте, если каким-то образом в функцию попал не массив, мы не узнаем об ошибке, и потом может бомбануть где-то в другом месте. Так что ok.

2022-12-15 20:39 UTC, ipetropolsky commented on index.js
> +        return value.constructor.name.toLowerCase();
Классный приём! Но что-то с простым объектом не работает: `{}`

2022-12-15 20:39 UTC, ipetropolsky commented on index.js
> +            return '-Infinity';
Это можно проверить сравнением с `-Infinity`, как-то более явно будет. Просто сейчас в этом месте нужно держать в голове 4 условия, проверенные выше, чтобы понимать, в каких случаях мы сюда попадём.

2022-12-15 20:39 UTC, ipetropolsky commented on index.js
> +    return set.size === arr.length;
👍

2022-12-15 20:39 UTC, ipetropolsky commented on index.js
> +    return Object.entries(result).sort();
Я тут ничего не вижу про сортировку массива из массивов: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
Можно предположить, что это работает, потому что каждый подмассив приводится к строке, и у неё в начале оказывается ключ, по которому мы и сортируем. Но давай лучше явно укажем функцию сортировки, чтобы потом не гадать, что тут за магия.

2022-12-15 20:39 UTC, ipetropolsky commented on index.js
> +test('Two arrays are not equal (length)', compareTowArrays([1, 2, 3], [1, 2, 3, 4]), false);
Хороший тест, не очевидный ) Если не проверить длину в функции сравнения, может выдать `true`.

2022-12-15 21:43 UTC, Beken-S commented on index.js
> +    } while (tasksA.length > 0);
Просто для блока тестов countRealTypes вроде надо сравнивать многомерные массивы поэтому решил сразу реализовать функцию с такой возможностью. 
Сделал не через рекурсию т.к. хотел чтобы она была более универсальная, а как реализовать хвостовую рекурсию чтобы не было возможности переполнения стека не разобрался.

2022-12-15 21:59 UTC, Beken-S commented on index.js
> +        return value.constructor.name.toLowerCase();
![Снимок экрана от 2022-12-16 00-52-44](https://user-images.githubusercontent.com/84242545/207975355-fa6e005c-4fd2-435b-bc9b-3da9ac7791ae.png)
У меня вроде работате.
Или имелось в виду с литералом?
Надо переделать?

2022-12-15 22:00 UTC, Beken-S commented on index.js
> +            return '-Infinity';
Действительно, что-то не додумался что так просто можно сделать :)

2022-12-16 16:02 UTC, Beken-S commented on index.js
> +    return Object.entries(result).sort();
[Fix countRealTypes](https://github.com/Beken-S/js-part-0/pull/1/commits/d99a08afa10f020d9cf801b1968e5cb725fd5280)

2022-12-16 16:05 UTC, Beken-S commented on index.js
> +            return '-Infinity';
Исправил.
[Fix getRealType](https://github.com/Beken-S/js-part-0/pull/1/commits/516fae3dcc02b06889deff2a2e37b4d4959aeb99)

2022-12-16 16:07 UTC, Beken-S commented on index.js
> +        return value.constructor.name.toLowerCase();
Вроде сделал более правильно. Или всё-таки сделать через instanceof?
[Fix getRealType](https://github.com/Beken-S/js-part-0/pull/1/commits/516fae3dcc02b06889deff2a2e37b4d4959aeb99)

2022-12-16 16:14 UTC, Beken-S commented on index.js
> +    } while (tasksA.length > 0);
Сделал через рекурсию.
[Fix compareTowArrays](https://github.com/Beken-S/js-part-0/pull/1/commits/384c9fb171c4992d997a73e76b266917dd9a874a)

2022-12-16 19:00 UTC, Beken-S commented on index.js
> +    } while (tasksA.length > 0);
Сделал через рекурсию. 22d94de050e8ab0d3021047f07ec267568a88044

2022-12-16 19:17 UTC, Beken-S commented on index.js
> +        return Object.prototype.toString.call(value).slice(8, -1).toLowerCase();
Или сделать всё-таки через instanceof?

2022-12-20 22:01 UTC, ipetropolsky approved these changes

2022-12-20 22:01 UTC, ipetropolsky commented on index.js
> +        return Object.prototype.toString.call(value).slice(8, -1).toLowerCase();
А зачем поменял, где-то не работает? Про объект обсудили, я ошибся. Вроде было удобнее, чем через `toString`.

2022-12-20 22:01 UTC, ipetropolsky commented on index.js
> +        return value.toString();
Лучше всё же явно вернуть строку, её потом можно найти поиском, глазами прочитать и всё такое.

2022-12-21 06:32 UTC, Beken-S commented on index.js
> +        return Object.prototype.toString.call(value).slice(8, -1).toLowerCase();
Изначально посчитал не существенной возможность переопределения конструктора стандартных объектов, но вопрос про обычный объект побудил более подробно изучить плюсы и минусы этих методов и я так понял, что лучшей практикой все таки является этот метод.

2022-12-21 06:45 UTC, Beken-S commented on index.js
> +        return value.toString();
```suggestion
        return value.toString(); // 'NaN', 'Infinity', '-Infinity'
```
А так имеет право на жизнь?

Или так в любом случае лучше:
``` suggestion
        if (type === 'number') {
            if (Number.isNaN(value)) {
                return 'NaN';
            }
            if (value === -Infinity) {
                return 'Infinity';
            }
            if (value === Infinity) {
                return 'Infinity';        
            }
            return type;
        }
```

2022-12-28 20:25 UTC, merged